version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nas-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nas-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default

networks:
  default:
    driver: bridge






