version: '3.8'

services:
  iahome-app:
    image: iahome:latest
    container_name: iahome-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    networks:
      - iahome-network
    volumes:
      - iahome_logs:/app/logs
      - iahome_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iahome.rule=Host(`iahome.fr`) || Host(`www.iahome.fr`)"
      - "traefik.http.routers.iahome.entrypoints=websecure"
      - "traefik.http.routers.iahome.tls.certresolver=letsencrypt"
      - "traefik.http.services.iahome.loadbalancer.server.port=3000"
      - "traefik.docker.network=iahome-network"

  iahome-nginx:
    image: nginx:alpine
    container_name: iahome-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - iahome_nginx_logs:/var/log/nginx
    depends_on:
      - iahome-app
    networks:
      - iahome-network
    labels:
      - "traefik.enable=false"

  # Traefik pour la gestion automatique des certificats SSL
  traefik:
    image: traefik:v2.10
    container_name: iahome-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@iahome.fr"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - iahome_letsencrypt:/letsencrypt
    networks:
      - iahome-network
    labels:
      - "traefik.enable=false"

networks:
  iahome-network:
    driver: bridge

volumes:
  iahome_logs:
    driver: local
  iahome_uploads:
    driver: local
  iahome_nginx_logs:
    driver: local
  iahome_letsencrypt:
    driver: local 